version: '3'

services:
  localstack:
    image: localstack/localstack:0.10.8
    ports:
      - 4568:4568
      - 8080:8080
    environment:
      - SERVICES=kinesis:4568

  router:
    image: liveintentberlin/qa-challenge:0.0.1
    depends_on:
      - localstack
    entrypoint: "/bin/bash -c"
    command: "'sleep 10; rm -f /opt/docker/RUNNING_PID && bin/qa-challenge'"
    ports:
      - 9000:9000
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - KINESIS_SERVICE_ENDPOINT=http://localstack:4568
